version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: iksaas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: iksaas
      POSTGRES_PASSWORD: iksaas
      POSTGRES_DB: iksaas
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: iksaas-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  pg_data:
